name: Generate Datas
on:
schedule: # execute every 12 hours
- cron: "* */12 * * *"
workflow_dispatch:
jobs:
build:
name: Jobs to update datas
runs-on: ubuntu-latest
steps:
# Summary Cards
- usa: ações/checkout@v2
- usa: vn7n24fzkq/github-profile-summary-cards@release
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
com:
USERNAME: ${{ dgiovana22}}

      # Animação de Cobra
      - usa : Platane/snk@master
        id : cobra-gif
